Redesigned navbar
gurkult/reagurk pull request #33
Opened 2021-01-09 19:02 UTC by RandomDev26

Redesigned the Navbar and made it into its own component.

2021-01-29 01:47 UTC, fisher60 requested changes
This looks pretty good, just some minor changes>

I also think the white on yellow is *very* difficult to read, these colors should be tweaked 
![image](https://user-images.githubusercontent.com/39353605/106220702-eaf45c80-6190-11eb-85a0-9de11aa0a03c.png)

2021-01-29 01:47 UTC, fisher60 commented on reagurk/src/components/Navbar.jsx
> +                    </li>
The internal links should use the `NavLink` tag as they redirect to our React routes. The way they are programmed here treats this like a static site.

Going back to the home screen should have `target"_blank"` either, as that opens a new tab. The `a` tag should only be used when linking directly to an external site.

2021-01-29 01:47 UTC, fisher60 commented on reagurk/src/components/Navbar.jsx
> +                        <img src={gurkultImg} className="icon" alt="The gurkan" />
as a change, the gurkult logo should also link to the home page.

2021-05-03 06:44 UTC, gustavwilliam commented
We're moving on with another version of the site (and therefore NavBar). Regardless, thanks for the PR.

2021-05-03 06:44 UTC, closed without merging