Migrate to TypeScript and TailwindCSS
gurkult/reagurk pull request #41
Opened 2021-05-07 15:46 UTC by dawnofmidnight

This PR migrates to TypeScript and TailwindCSS and restarts the project.

Live deployment: https://gurkult.vercel.app

Preview: 
![image](https://user-images.githubusercontent.com/78233879/117475159-baf3ec80-af29-11eb-8143-8d954e371ef2.png)
![image](https://user-images.githubusercontent.com/78233879/117475257-cfd08000-af29-11eb-8a05-2d88618bfea1.png)

2021-05-21 05:46 UTC, fisher60 requested changes
Hello, this looks pretty good, but it looks like build files/dependencies were pushed as well, these should not be on the repo. Could you either remove these, or explain why they are here if I am mistaken?

2021-05-21 05:46 UTC, fisher60 commented on build/manifest.json
> +  "name": "Gurkult - A Kult for open source",
The wording here was very intentional. We are straying away from advertising as a `cult` as it is misleading and not really the message we wish to convey.

2021-05-21 05:46 UTC, fisher60 commented on build/manifest.json
> +      "src": "logo192.png",
may want to double check that these are the correct file names

2021-05-21 05:46 UTC, fisher60 commented on public/index.html
> +    <title>React App</title>
It appears intentional changes to the meta were reverted here. We need this to remain accurate so this will embed properly on discord.

2021-05-21 05:46 UTC, fisher60 commented on public/manifest.json
> +  "name": "Gurkult - A Kult for open source",
Branding has changed, not trying to refer to being a cult.

2021-05-21 10:34 UTC, dawnofmidnight commented
I completely forgot about those, I'll remove them soon.

2021-05-21 13:26 UTC, dawnofmidnight commented
All fixed, and `build` directory was removed.

2021-07-10 16:35 UTC, dawnofmidnight commented
`build` wasn't gitignored and ending up getting added back in https://github.com/gurkult/reagurk/pull/41/commits/30635dc64b1445b16efc69e48932fdd3cf34524a. I'll remove the build files again when I get a chance, and I gitignored it in https://github.com/gurkult/reagurk/pull/41/commits/fe1cfd66db5e6dbbadd65fc49f3ec0648d734554

2021-07-14 17:01 UTC, dawnofmidnight commented
This PR is actually finally ready. I think

2021-07-17 06:42 UTC, Arnav-2004 requested changes
This is a breaking change.

2021-07-17 06:43 UTC, Arnav-2004 requested changes

2021-07-17 06:43 UTC, Arnav-2004 commented on reagurk/src/index.tsx
> +import reportWebVitals from './reportWebVitals';
There is no `reportWebVitals` file.

2021-07-17 10:47 UTC, dawnofmidnight commented on reagurk/src/index.tsx
> +import reportWebVitals from './reportWebVitals';
Removed

2021-07-18 08:36 UTC, Arnav-2004 approved these changes
Looks good to me.

2021-08-13 19:33 UTC, fisher60 requested changes
Sorry, this is incredibly delayed. It all looks good, but I think we should be opening up new tabs for any link to an external site. This would allow someone to continue browsing the site, even if they wanted to take a look at our links. Need to remeber appropriate security changes as well (referrer, etc)

2021-08-13 20:03 UTC, dawnofmidnight commented
> Sorry, this is incredibly delayed. It all looks good, but I think we should be opening up new tabs for any link to an external site. This would allow someone to continue browsing the site, even if they wanted to take a look at our links. Need to remeber appropriate security changes as well (referrer, etc)

Addressed :)

2021-08-13 21:01 UTC, fisher60 approved these changes
You are an absolute savage. Ty so much for all your help/work. This is really fantastic work.

Griff approves as well.

2021-08-13 21:04 UTC, merged